#!/usr/bin/env python3

#
# Clean footnotes.yaml to remove duplicates and keep lists of urls sorted.
#
# usage: ./clean_footnotes footnotes.yaml
#


import sys
import yaml

if __name__ == '__main__':

    with open(sys.argv[1]) as f:
        orig = yaml.load(f)

    with open(sys.argv[1], mode='w') as f:
        yaml.dump({ k: sorted(list(set(v))) for k, v in orig.items() }, f, default_flow_style=False)
